// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3W2LTOIZ8fqCAY5moBby2RsQ3pgaEZxo',
    appId: '1:138999516205:web:d8ab44e1f6cf0709f4bca4',
    messagingSenderId: '138999516205',
    projectId: 'mobilebd1',
    authDomain: 'mobilebd1.firebaseapp.com',
    storageBucket: 'mobilebd1.appspot.com',
    measurementId: 'G-YY7SV689V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJJwOc5yflbYG5KjFolj2zN-4u8jZpdHw',
    appId: '1:138999516205:android:2c994d96abdd9fe9f4bca4',
    messagingSenderId: '138999516205',
    projectId: 'mobilebd1',
    storageBucket: 'mobilebd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5CQN_8EwnoHyPRvMofVLMMlQ2vRYpM84',
    appId: '1:138999516205:ios:ba06263440d58530f4bca4',
    messagingSenderId: '138999516205',
    projectId: 'mobilebd1',
    storageBucket: 'mobilebd1.appspot.com',
    iosBundleId: 'com.test.bd1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5CQN_8EwnoHyPRvMofVLMMlQ2vRYpM84',
    appId: '1:138999516205:ios:3ff69c16a223ea51f4bca4',
    messagingSenderId: '138999516205',
    projectId: 'mobilebd1',
    storageBucket: 'mobilebd1.appspot.com',
    iosBundleId: 'com.example.bd1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3W2LTOIZ8fqCAY5moBby2RsQ3pgaEZxo',
    appId: '1:138999516205:web:8d1bde094387ff22f4bca4',
    messagingSenderId: '138999516205',
    projectId: 'mobilebd1',
    authDomain: 'mobilebd1.firebaseapp.com',
    storageBucket: 'mobilebd1.appspot.com',
    measurementId: 'G-EL7MSLFGWV',
  );
}
